server:
  port: '8099'

spring:
  profiles:
    active: @activatedProperties@
  application:
    name: credits

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: 'true'
    restart:
      enabled: 'true'
      
backend:
  service:
    fees: 'http://fees/fees'